### PR TITLE
Regenerate API CLI  for clinical image library study

### PR DESCRIPTION
**Pull request by arnojsaha**

### CODE REVIEW

**Review by Laugslander — APPROVED** [review]

**Review by Laugslander — CHANGES_REQUESTED** [review]
@arnojsaha Please regenerate the API based on the Swagger definition of the entities service in the TEST deployment, since DEV is running a feature branch which includes new changes that should not yet be incorporated in the igtcloud-client.

**Review by koendelaat — CHANGES_REQUESTED** [review]

**Review by koendelaat — APPROVED** [review]

**Comment by arnojsaha** [comment]
> @arnojsaha Please regenerate the API based on the Swagger definition of the entities service in the TEST deployment, since DEV is running a feature branch which includes new changes that should not yet be incorporated in the igtcloud-client.

I have regenerated the CLI API based on the Swagger definition of entities service in TEST deployment

**Comment by arnojsaha** [comment]
> @arnojsaha Please regenerate the API based on the Swagger definition of the entities service in the TEST deployment, since DEV is running a feature branch which includes new changes that should not yet be incorporated in the igtcloud-client.

**Comment by arnojsaha** [comment]
The merging of the PR will be done after ms-entities is deployed in production

**Review by Laugslander — APPROVED** [review]

**Pull request merged**
